### ISSUE TITLE
Loading Notification

### ISSUE THREAD

**Issue by akreider** [AugurProject/turbo#1519] opened 2021-10-26 20:49 UTC
It might be useful to had a loading notification to indicate that the markets and your positions take time to load. For instance, after a trade it will often take 10-60 seconds for your portfolio and balance to reflect the trade outcome.

It would be especially useful if there was an estimate of how long this would take or an indication that the loading is complete.

Often after just doing a trade, the site will show that I have the position (often after waiting 10-20 seconds), remove it (apparently return my account to the pre-trade state), and then it will reappear.  For most people this behavior is very disturbing - and you can get yourself into trouble if you start doing multiple trades and one of them doesn't go through and causes a bottleneck (and then you may have to use custom nonces on metamask).

I'm using 1.5.0.

**Comment by bthaile** [comment] 2021-10-28 19:58
Yes this is an issue, main root of the problem is requestion data from polygon rpc nodes often fail. Best solution would be for the user to have their own dedicated rpc server they can rely on. The public rpc endpoints are unreliable. 

We have a ticket to update user balances after contract interaction instead of on a timer.  Added task on the following ticket to better inform the user their balances are being updated. Thanks for the suggestion.
https://github.com/AugurProject/turbo/issues/1477

closing

**Closed as completed by bthaile** 2021-10-28 19:58 UTC
