### ISSUE TITLE
Don't deploy new USDC collateral contract

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#260] opened 2021-04-21 00:05 UTC
Don't deploy new USDC collateral contract each deployment. 
Matic already has USDC, so might as well get ready

**Comment by justinbarry** [comment] 2021-04-21 17:51
We will get this for free after we merge #214

**Comment by justinbarry** [comment] 2021-04-21 20:13
Closing as a dupe of #158

**Closed as completed by justinbarry** 2021-04-21 20:13 UTC
Labels: solidity
